task 5 to 7
StevenJune/be_my_ncnews pull request #3
Opened 2022-09-07 07:42 UTC by StevenJune

Task 5 to 7

2022-09-07 09:00 UTC, Rayhaan2k9 commented on __tests__/app.test.js
> +  it("status:201, responds with invalid post key", () => {
This should be a 400

2022-09-07 09:01 UTC, Rayhaan2k9 commented on __tests__/app.test.js
> +       .expect(400)
This should be a 404 as the article id is a number but doesn't exist

2022-09-07 09:02 UTC, Rayhaan2k9 commented on __tests__/app.test.js
> +  test.only("status:400, invalid article_id feed in", () => {
Don't forget to remove the .only from your tests!

2022-09-07 09:02 UTC, Rayhaan2k9 commented on __tests__/app.test.js
> +
You could also add 1 more test here. What if inc_votes is not a number?

2022-09-07 09:14 UTC, Rayhaan2k9 commented on __tests__/app.test.js
> +        .get(`/api/articles/${article_id}/comment`)
This endpoint url is incorrect. It should just be an update to your existing /api/articles/:article_id

2022-09-07 09:16 UTC, Rayhaan2k9 commented on app.js
> +app.get("/api/articles/:article_id/comment", getArticlesByIdComment);
This endpoint url is incorrect. You don't need to create a new endpoint, you just need to add some code to your existing /api/articles/:article_id

2022-09-07 09:17 UTC, Rayhaan2k9 requested changes
A few things that need to be fixed Steven. I have left comments for you. The main thing is ticket 7. This doesn't need to be a new endpoint. It is /api/articles/:article_id. You can just update your code in that endpoint for ticket 7 :)

2022-09-08 10:00 UTC, leekli requested changes
Hi Steven, this pull request still is not quite finished.

There are some comments attached I would like you to look at:
* There is some commented out code and a console log which needs removing 
* I can see functions for 'searchingArticlesByTopic' - I am not sure why these are here? they are not part of tickets 5-7? Why are these here? If it's because ticket 8 asks for articles by topic, then you should not be working on ticket 8 yet, you only do ticket 8 tasks once and only once tickets 5-7 have been approved. Please can you remove any search articles by topic functions and tests.

2022-09-08 10:00 UTC, leekli commented on app.js
> +//app.get("/api/articles/:article_id", getArticlesById);  is going to be replaced by function getArticlesByIdComment
Please remove this commented out code

2022-09-08 10:00 UTC, leekli commented on app.js
> +//app.get("/api/articles?topic=:topic", getArticlesByTopic);
Please remove this commented out code

2022-09-08 10:00 UTC, leekli commented on app.js
> +//app.get("/api/articles", getArticlesByTopic);
Please remove this commented out code

2022-09-08 10:00 UTC, leekli commented on app.js
> +    console.log(err);
This console log does not need to be here

2022-09-08 10:00 UTC, leekli commented on controllers/news.js
> +};
Steven - What ticket is this function for? It's not in tickets 5-7 so I am not sure why you have this function here? There is not an endpoint for it in your app.js either. Are you trying to start ticket 8 here? If so, you shouldn't be working on ticket 8 until tickets 5-7 have been approved.

2022-09-08 10:00 UTC, leekli commented on models/news.js
> -
Steven - What ticket is this function for? It's not in tickets 5-7 so I am not sure why you have this function here? There is not an endpoint for it in your app.js either. Are you trying to start ticket 8 here? If so, you shouldn't be working on ticket 8 until tickets 5-7 have been approved.

2022-09-08 10:29 UTC, leekli approved these changes
Thank you, Steve.

You can now MERGE this branch.

Please now move on to ticket number 8 only, please only work on 1 ticket at a time in each branch, please do not try to complete ticket 9 at the same time. If you have any questions, then please ask us.

2022-09-08 10:33 UTC, merged