commit for Task 8
StevenJune/be_my_ncnews pull request #4
Opened 2022-09-08 10:43 UTC by StevenJune

Task 8

2022-09-08 11:01 UTC, leekli requested changes
Hi, request for changes:
* Remove console log on line 233 in app.test.js
* Check line 246 in app.test.js - the Trello Board instructions do not want us to return 'body' in the query on /api/articles endpoint
* It may be worth having an expect statement to check how many articles have been returned with the topic of 'mitch', for example if there are 5 articles in the database with a topic of 'mitch' then you would expect a length of 5.
* Have a think about some extra tests such as: 400 invalid topic, 404 topic not found, 200 for an topic that exists but has no articles

Please have a look at these actions, and once complete please submit a new pull request review.

2022-09-08 11:01 UTC, leekli commented on __tests__/app.test.js
> +        console.log(body, "<<<body");
Please remove this console log

2022-09-08 11:01 UTC, leekli commented on __tests__/app.test.js
> +              body: expect.any(String),
Please re-check the Trello Board instructions - it doesn't want us to return the body key in /api/articles, this needs to be removed in the model and then the test

2022-09-08 11:01 UTC, leekli commented on __tests__/app.test.js
> +});
Have a think about some extra tests such as:
* 400 invalid topic
* 404 topic not found
* 200 for an topic that exists but has no articles

2022-09-09 08:27 UTC, Rayhaan2k9 commented on models/news.js
> +        console.log(result, "goto error step 031");
Please remove the console log

2022-09-09 08:28 UTC, Rayhaan2k9 commented on models/news.js
> +      console.log("setup 04");
Please remove the console log

2022-09-09 08:29 UTC, Rayhaan2k9 approved these changes
Great work Steven :) Please remove the console logs, make a pull request and then merge it. You don't need to send it to us

2022-09-09 08:47 UTC, merged